name: Aubase IG go-publish

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base    # use ig publisher base image
    steps:
    - name: Checkout AU base Repository
      uses: actions/checkout@v4
      repo: hl7au/au-fhir-base
      with:
        path: aubase

    - name: Checkout IG History Template Repository
      uses: actions/checkout@v4
      repo: HL7/fhir-ig-history-template
      with:
        path: fhir-history
      
    - name: Checkout IG Registry Repository
      uses: actions/checkout@v4
      repo: hl7au/ig-registry
      with:
        path: ig-registry

    - name: Update Publisher
      working-directory: ./aubase
      run: |
        _updatePublisher.sh -f -y

    - name: Basic Publish for Aubase
      run: |
        java -jar input-cache/publisher.jar -ig ./hl7au/au-fhir-base/ig.ini -publish -target https://build.fhir.org.au/ig/hl7au/au-fhir-base/branches/example 

    - name: Create directories
      run: |
        mkdir -p webroot/fhir/base

    - name: Download package-list.json
      run: |
        del aubase/package-list.json
        curl --output webroot/fhir/base/package-list.json --url https://hl7.org.au/fhir/base/package-list.json

    - name: Download package-feed.xml
      run: |
        curl --output webroot/fhir/package-feed.xml --url https://hl7.org.au/fhir/package-feed.xml

    - name: Download publication-feed.xml
      run: |
        curl --output webroot/fhir/publication-feed.xml --url https://hl7.org.au/fhir/publication-feed.xml

    - name: Generate Package Registry
      run: |
        java -jar input-cache/publisher.jar -generate-package-registry webroot

    - name: Run Aubase Publisher build
      run:  java -jar ./input-cache/publisher.jar -go-publish -source ./hl7au/au-fhir-base -web ./webroot -history ./fhir-history -registry ./ig-registry/fhir-ig-list.json # -ig ig.ini -source . 

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-output
        path: aubase/output/full-ig.zip # full ig zip is 1/10 the size but has all relevant content?


    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: gopublish-output
        path: aubase/output/full-ig.zip # full ig zip is 1/10 the size but has all relevant content?


    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.BUILD_SERVER}} # change to be env variable to support multiple environments later on
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: aubase/output/
        server-dir: /ig/hl7au/au-fhir-base/branches/${{ github.ref }}/gopublish/
        dry-run: true