name: Au Core IG Profiles publish->go-publish

on:
  repository_dispatch:
    types: [tag_created]


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base    # use ig publisher base image
    strategy:
      matrix:
        project: ['core'] # base has error ```This website does not have an entry in the layout rules in /tmp/web-root/run-20240228/publish-setup.json to publish the IG with Package Id 'hl7.fhir.au.base'"```
    steps:
    - name: Echo payload
      run: |
        echo "Repo: ${{ github.event.client_payload.repository }}"
        echo "Tag: ${{ github.event.client_payload.tag }}"
        echo "Ref: ${{ github.event.client_payload.ref }}"
        echo "Action: ${{ github.event.client_payload.action }}"
        echo "Sender: ${{ github.event.client_payload.sender }}"
        echo "Payload: ${{ github.event.client_payload }}"

    - name: Checkout Publications Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials from GitHub OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::966489602583:role/ghactions_publications_oidc
        aws-region: ap-southeast-2
        
    - name: Checkout AU ${{matrix.project}} Repository
      uses: actions/checkout@v4
      with:
        repository: hl7au/au-fhir-${{matrix.project}}
        path: hl7au/au-fhir-${{matrix.project}}

    - name: Checkout IG History Template Repository
      uses: actions/checkout@v4
      with:
        repository: HL7/fhir-ig-history-template
        path: fhir-history
    
    - name: Checkout IG Registry Repository
      uses: actions/checkout@v4
      with:
        repository: hl7au/ig-registry
        path: ig-registry

    - name: Update Publisher
      run: |
        echo "Updating Publisher"
        ./_updatePublisher.sh -f -y

          
    - name: Basic Publish for Au${{matrix.project}}
      run: |
          echo "Generating Publish for  Au${{matrix.project}} IG..."
          java -jar input-cache/publisher.jar -ig hl7au/au-fhir-${{matrix.project}}/ig.ini

    - name: Create directories
      run: |
        mkdir -p webroot/fhir/${{matrix.project}}

    - name: Download package-list.json
      run: |
        rm -rf hl7au/au-fhir-${{matrix.project}}/package-list.json
        URL="https://hl7.org.au/fhir"
        if [ "${{ matrix.project }}" == "base" ]; then
          FULL_URL="$URL/package-list.json"
        else
          FULL_URL="$URL/${{ matrix.project }}/package-list.json"
        fi
        
        curl --output webroot/fhir/${{ matrix.project }}/package-list.json --url $FULL_URL

    - name: Download package-feed.xml
      run: |
        curl --output webroot/fhir/package-feed.xml --url https://hl7.org.au/fhir/package-feed.xml

    - name: Download publication-feed.xml
      run: |
        curl --output webroot/fhir/publication-feed.xml --url https://hl7.org.au/fhir/publication-feed.xml

    - name: Generate Package Registry
      run: |
        java -jar input-cache/publisher.jar -generate-package-registry webroot

    - name: Run Au${{matrix.project}} Publisher build
      run:  java -jar ./input-cache/publisher.jar -go-publish -source ./hl7au/au-fhir-${{matrix.project}} -web ./webroot -history ./fhir-history -registry ./ig-registry/fhir-ig-list.json -templates ./templates -tx https://txreg.azurewebsites.net/txdev

    - name: List directories
      run:  |
        find . -type d

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-output
        path: webroot/fhir/${{matrix.project}}

    # - name: 📂 Sync files # ftp is incredibly slow > 30 min sometimes, costing compute and efficency 
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: ${{secrets.BUILD_SERVER}} # change to be env variable to support multiple environments later on
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: au${{matrix.project}}/output/
    #     server-dir: /ig/hl7au/au-fhir-${{matrix.project}}/branches/${{ github.ref }}/gopublish/
    #     dry-run: true

    - name: Upload artifacts to S3
      run: aws s3 cp ./webroot s3://hl7au-fhir-ig/core --recursive