
name: Au IG Profiles Go Publish on Tag Creation

on:
  repository_dispatch:
    types: [tag_created]
  pull_request:
    branches:
      - '*'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base
    strategy:
      matrix:
        repo: [au-fhir-core, au-fhir-base]
    steps:
      - name: Checkout Publications Repository
        uses: actions/checkout@v4
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')

      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        with:
          role-to-assume: arn:aws:iam::966489602583:role/ghactions_publications_oidc
          aws-region: ap-southeast-2

      - name: Checkout AU Repository
        uses: actions/checkout@v4
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        with:
          repository: hl7au/${{ matrix.repo }}
          path: hl7au/${{ matrix.repo }}

      - name: Checkout IG History Template Repository
        uses: actions/checkout@v4
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        with:
          repository: HL7/fhir-ig-history-template
          path: fhir-history

      - name: Checkout IG Registry Repository
        uses: actions/checkout@v4
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        with:
          repository: hl7au/ig-registry
          path: ig-registry

      - name: Update Publisher
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          echo "Updating Publisher"
          ./_updatePublisher.sh -f -y

      - name: Basic Publish for AU IG
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          echo "Generating Publish for ${matrix.repo} IG..."
          java -jar input-cache/publisher.jar -ig hl7au/${{ matrix.repo }}/ig.ini

      - name: Create directories
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          mkdir -p webroot/fhir/${{ matrix.repo }}

      - name: Download package-list.json
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          rm -rf hl7au/au-fhir-${{matrix.project}}/package-list.json
          URL="https://hl7.org.au/fhir"
          if [ "${{ matrix.project }}" == "base" ]; then
            FULL_URL="$URL/package-list.json"
          else
            FULL_URL="$URL/${{ matrix.project }}/package-list.json"
          fi
          
          curl --output webroot/fhir/${{ matrix.project }}/package-list.json --url $FULL_URL

      - name: Download package-feed.xml
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          curl --output webroot/fhir/package-feed.xml --url https://hl7.org.au/fhir/package-feed.xml

      - name: Download publication-feed.xml
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          curl --output webroot/fhir/publication-feed.xml --url https://hl7.org.au/fhir/publication-feed.xml

      - name: Generate Package Registry
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          java -jar input-cache/publisher.jar -generate-package-registry webroot

      - name: Run AU IG Publisher build
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          java -jar ./input-cache/publisher.jar -go-publish -source ./hl7au/${{ matrix.repo }} -web ./webroot -history ./fhir-history -registry ./ig-registry/fhir-ig-list.json -templates ./templates -tx https://txreg.azurewebsites.net/txdev

      - name: List directories
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: |
          find . -type d

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        with:
          name: publish-output
          path: webroot/fhir/${{ matrix.repo }}

      - name: Upload artifacts to S3
        if: |
          (github.event.client_payload.repository == 'au-fhir-core' && matrix.repo == 'au-fhir-core') ||
          (github.event.client_payload.repository == 'au-fhir-base' && matrix.repo == 'au-fhir-base')
        run: aws s3 cp ./webroot s3://hl7au-fhir-ig/${{ matrix.repo }} --recursive